# This workflow checks out code, builds an image, performs a container image
# scan, evaluates the image, and promotes it if it passes.

name: Grype Demo

on: 
  #push:
  #  branches:
  #    - main
  #schedule:
  #  - cron: '42 20 */14 * *'
  workflow_dispatch:

### Least-privilege by default
permissions:
  contents: read
env:
  REGISTRY: ghcr.io           ### if you change this you will probably need to update the build section to handle registry credentials  

jobs:

  build:
    name: Image Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
    - name: "Set IMAGE Environmental Variable"
      id: set_image
      run: |
        IMAGE="${REGISTRY}/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}"
        echo "image=${IMAGE,,}" >> "$GITHUB_OUTPUT"                 
        ### ${IMAGE,,} makes sure it's all lowercase
    - name: Checkout Code
      uses: actions/checkout@v6
    - name: Log in to the Container Registry
      uses: docker/login-action@v4
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Build and push container
      uses: docker/build-push-action@v7
      with:
        context: .
        tags: ${{ steps.set_image.outputs.image }}
        push: true
        
  scan:
    name: Image Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions: 
      contents: write
      security-events: read
    needs: [build]
    steps:
    - name: Install Tools
      ### grab the latest versions of syft and grype
      ### the PATH assignment isn't strictly necessary (/usr/local/bin is in the default path, just further down the list,
      ### this just moves it up to the first thing we look at)
      run: |
        curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b /usr/local/bin
        curl -sSfL https://get.anchore.io/grype | sudo sh -s -- -b /usr/local/bin
        export PATH="/usr/local/bin/:$PATH"
    - name: Generate SBOM
      ### option notes:
      ### -o syft-table sends human-readable output to console
      ### -o json generates native syft sbom in json format for the vuln scan and for archiving
      ###
      ### if you also need a particular format for audit/regulator (e.g. spdx, cyclonedx), you
      ### can just add additional -o parameters as needed.
      ###
      ### output file is $(basename ${GITHUB_REPOSITORY,,}).sbom.json which will just make sure we
      ### get an all-lowercase repo name without slashes etc.
      ### input is ${{ needs.build.outputs.image }} which is just the output of the previous build job
      run: |
        syft -o syft-table -o json=$(basename ${GITHUB_REPOSITORY,,}).sbom.json ${{ needs.build.outputs.image }}
    - name: Generate Vulnerability Report 
      ### -o table outputs human-readable to console
      ### -o json outputs archiveable json to file
      ### -o sarif outputs a format that the github security dashboard uses
      ### input and output files follow the format we used in the SBOM generation step above.
      ###
      ### if we want to break the pipeline if vulnerabilities of a certain
      ### severity are found, we can use the -f option e.g.
      ### grype -o json -f high image:tag
      ### if we don't want to gate on that and instead just want
      ### to generate reports, just remove the -f flag.
      run: | 
        grype -o table -o json=$(basename ${GITHUB_REPOSITORY,,}).vuln.json -o sarif=$(basename ${GITHUB_REPOSITORY,,}).sarif file:$(basename ${GITHUB_REPOSITORY,,}).sbom.json 
        ls

    ### Alternatively, you can use the sbom-action and scan-action, 
    ### I prefer using syft and grype directly since you get more 
    ### control (particularly with outputs)
    #- name: Generate SBOM
    #  uses: anchore/sbom-action@v0
    #  id: sbom
    #  with:
    #    image: ${{ needs.build.outputs.image }}
    #    registry-username: ${{ github.actor }}
    #    registry-password: ${{ secrets.GITHUB_TOKEN }}
    #    output-file: sbom.json
    #    format: json
    #    dependency-snapshot: true
    #    upload-artifact-retention: 14
    #- name: Generate Vulnerability Repot
    #  id: scan
    #  uses: anchore/scan-action@v7
    #  with:
    #    sbom: sbom.json
    #    fail-build: true
    #    severity-cutoff: critical
    
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: ./$(basename ${GITHUB_REPOSITORY,,}).sarif
    - name: Archive Vulnerability Report
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: vuln-report
        path: ./$(basename ${GITHUB_REPOSITORY,,}).vuln.json
        retention-days: 14
    - name: Archive SBOM
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: sbom
        path: ./$(basename ${GITHUB_REPOSITORY,,}).sbom.json
        retention-days: 14

  ### if everything succeeds, then you can continue with your normal pipeline activities (promote image, do QA tests, whatever) 
  ##Promote:
  ##  needs: Grype-Check
  ##  runs-on: ubuntu-latest
  ##  steps:
  ##  - name: Login to ghcr.io
  ##    run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
  ##  - name: Re-Tag Image
  ##    run: |
  ##      docker pull ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_SHA}
  ##      docker tag ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_SHA} ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF_NAME}
  ##  - name: Push Docker Image
  ##    run: |
  ##      docker push ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF_NAME}
